### ISSUE TITLE
Need Update for Angular 15 & 16

### ISSUE THREAD

**Issue by prasantht96** [jadengis/ngx-clarity#1]

**Comment by jadengis** [comment]
Hi @prasantht96. Thanks for opening the issue. I realize this library is a few versions behind. Happy to update it.

Just so I know, do you need a version for Angular 15 or 16? I'm a little out of the loop and I'm not sure if I can make a version that is compatible with both.

After all the standalone component stuff, I'm thinking I can ditch the `NgModule` for a simple provider function like how Angular router works now.

**Comment by prasantht96** [comment]
Hi @jadengis 
Thank you for offering to update the library. I appreciate your help with this. Regarding the version compatibility, I currently require a version that is compatible with Angular 15.

Additionally, if possible, could you please consider updating the library to be compatible with Angular 16 when you have time in the future? This would not only benefit me but also other users who may be using Angular 16 or planning to upgrade to it.

Once again, thank you for your assistance, and I look forward to the updated version.

**Comment by jadengis** [comment]
Hi @prasantht96! Sorry for the delay but I've just released `ngx-clarity` v2.0.0 which include support for Angular 15 and 16. 

As an FYI the API has changed slightly to better support module-free applications. No huge changes are required, just replacing your call to `NgxClarityModule.forRoot` to a call to `provideClarity` in the providers array.

Hope that helps! Let me know if it works for you.

**Comment by prasantht96** [comment]
Thank you for the update! I have implemented it in my Angular 15 project, and it is working perfectly fine.
