### ISSUE TITLE
Angular 17 Update

### ISSUE THREAD

**Issue by prasantht96** [jadengis/ngx-clarity#5]

**Comment by jadengis** [comment]
@prasantht96 this should be easy to do. Is there anything about the API that you think needs to change with Angular 17? I haven't Looked too closely at the update yet.

**Comment by prasantht96** [comment]
> @prasantht96 this should be easy to do. Is there anything about the API that you think needs to change with Angular 17? I haven't Looked too closely at the update yet.

I believe that no changes are necessary for the ngx-clarity package to be compatible with Angular 17, except for updating the version.

**Comment by jadengis** [comment]
@prasantht96 I just published v2.1.0 which contains the version range bump we merged yesterday. Let me know if it works for you. Thanks again!

**Comment by prasantht96** [comment]
> @prasantht96 I just published v2.1.0 which contains the version range bump we merged yesterday. Let me know if it works for you. Thanks again!

It's Working. Thank you.
