### ISSUE TITLE
Angular 18 support

### ISSUE THREAD

**Issue by crswebb** [jadengis/ngx-clarity#8]
I'm using this package and it's not compatible with Angular 18.
Is there a planned update?

**Comment by jadengis** [comment]
Hi Stefan! As far as I am aware, this library shouldn't require any API updates to support Angular 18, and so the only required change would be a version bump. I can probably just whip up a PR to do that if you don't have any other feature requests.

**Comment by crswebb** [comment]
All I want is to use the package with Angular 18, no other features.
It does what I expect from it, good job!

Från: John Dengis ***@***.***>
Skickat: den 22 juni 2024 05:48
Till: jadengis/ngx-clarity ***@***.***>
Kopia: Stefan Bergfeldt ***@***.***>; Author ***@***.***>
Ämne: Re: [jadengis/ngx-clarity] Angular 18 support (Issue #8)


Hi Stefan! As far as I am aware, this library shouldn't require any API updates to support Angular 18, and so the only required change would be a version bump. I can probably just whip up a PR to do that if you don't have any other feature requests.

**Comment by jadengis** [comment]
@crswebb I've updated the library to support Angular 18 with wth release of version v2.2.0. Please let me know if this works for you! Thanks!
